kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qbrandegeei_BJSB3.pkdat.gz | cut -f 1 > Qarizonica_Qbrandegeei_BJSB3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qbrandegeei_BJSL25.pkdat.gz | cut -f 1 > Qarizonica_Qbrandegeei_BJSL25_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qbrandegeei_BJVL19.pkdat.gz | cut -f 1 > Qarizonica_Qbrandegeei_BJVL19_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qchrysolepis.pkdat.gz | cut -f 1 > Qarizonica_Qchrysolepis_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qdouglasii.pkdat.gz | cut -f 1 > Qarizonica_Qdouglasii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qdurata.pkdat.gz | cut -f 1 > Qarizonica_Qdurata_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qengelmannii.pkdat.gz | cut -f 1 > Qarizonica_Qengelmannii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qfusiformis_MXED8.pkdat.gz | cut -f 1 > Qarizonica_Qfusiformis_MXED8_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qarizonica_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qarizonica_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qarizonica_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qarizonica_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qarizonica_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qarizonica_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qarizonica_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qarizonica_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qarizonica_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qarizonica_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qarizonica_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qarizonica_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qarizonica_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qarizonica_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qarizonica_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qarizonica_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qarizonica_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qarizonica_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qarizonica_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qarizonica_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qarizonica_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qarizonica_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qarizonica_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qarizonica_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qarizonica.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qarizonica_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qbrandegeei_BJSL25.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qbrandegeei_BJSL25_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qbrandegeei_BJVL19.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qbrandegeei_BJVL19_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qchrysolepis.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qchrysolepis_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qdouglasii.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qdouglasii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qdurata.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qdurata_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qengelmannii.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qengelmannii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qfusiformis_MXED8.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qfusiformis_MXED8_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSB3.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qbrandegeei_BJSB3_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qbrandegeei_BJVL19.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qbrandegeei_BJVL19_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qchrysolepis.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qchrysolepis_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qdouglasii.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qdouglasii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qdurata.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qdurata_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qengelmannii.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qengelmannii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qfusiformis_MXED8.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qfusiformis_MXED8_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJSL25.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qbrandegeei_BJSL25_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qchrysolepis.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qchrysolepis_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qdouglasii.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qdouglasii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qdurata.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qdurata_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qengelmannii.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qengelmannii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qfusiformis_MXED8.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qfusiformis_MXED8_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qbrandegeei_BJVL19.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qbrandegeei_BJVL19_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qdouglasii.pkdat.gz | cut -f 1 > Qchrysolepis_Qdouglasii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qdurata.pkdat.gz | cut -f 1 > Qchrysolepis_Qdurata_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qengelmannii.pkdat.gz | cut -f 1 > Qchrysolepis_Qengelmannii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qfusiformis_MXED8.pkdat.gz | cut -f 1 > Qchrysolepis_Qfusiformis_MXED8_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qchrysolepis_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qchrysolepis_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qchrysolepis_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qchrysolepis_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qchrysolepis_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qchrysolepis_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qchrysolepis_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qchrysolepis_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qchrysolepis_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qchrysolepis_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qchrysolepis_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qchrysolepis_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qchrysolepis_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qchrysolepis_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qchrysolepis_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qchrysolepis_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qchrysolepis_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qchrysolepis_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qchrysolepis_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qchrysolepis_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qchrysolepis_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qchrysolepis_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qchrysolepis_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qchrysolepis_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qchrysolepis.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qchrysolepis_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qdurata.pkdat.gz | cut -f 1 > Qdouglasii_Qdurata_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qengelmannii.pkdat.gz | cut -f 1 > Qdouglasii_Qengelmannii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qfusiformis_MXED8.pkdat.gz | cut -f 1 > Qdouglasii_Qfusiformis_MXED8_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qdouglasii_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qdouglasii_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qdouglasii_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qdouglasii_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qdouglasii_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qdouglasii_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qdouglasii_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qdouglasii_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qdouglasii_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qdouglasii_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qdouglasii_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qdouglasii_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qdouglasii_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qdouglasii_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qdouglasii_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qdouglasii_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qdouglasii_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qdouglasii_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qdouglasii_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qdouglasii_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qdouglasii_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qdouglasii_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qdouglasii_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qdouglasii_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdouglasii.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qdouglasii_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qengelmannii.pkdat.gz | cut -f 1 > Qdurata_Qengelmannii_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qfusiformis_MXED8.pkdat.gz | cut -f 1 > Qdurata_Qfusiformis_MXED8_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qdurata_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qdurata_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qdurata_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qdurata_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qdurata_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qdurata_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qdurata_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qdurata_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qdurata_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qdurata_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qdurata_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qdurata_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qdurata_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qdurata_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qdurata_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qdurata_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qdurata_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qdurata_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qdurata_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qdurata_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qdurata_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qdurata_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qdurata_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qdurata_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qdurata.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qdurata_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qfusiformis_MXED8.pkdat.gz | cut -f 1 > Qengelmannii_Qfusiformis_MXED8_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qengelmannii_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qengelmannii_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qengelmannii_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qengelmannii_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qengelmannii_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qengelmannii_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qengelmannii_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qengelmannii_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qengelmannii_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qengelmannii_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qengelmannii_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qengelmannii_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qengelmannii_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qengelmannii_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qengelmannii_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qengelmannii_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qengelmannii_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qengelmannii_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qengelmannii_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qengelmannii_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qengelmannii_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qengelmannii_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qengelmannii_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qengelmannii_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qengelmannii.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qengelmannii_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qfusiformis_MXGT4.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qfusiformis_MXGT4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXED8.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qfusiformis_MXED8_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qfusiformis_TXGR3.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qfusiformis_TXGR3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_MXGT4.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qfusiformis_MXGT4_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qfusiformis_TXMD3.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qfusiformis_TXMD3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXGR3.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qfusiformis_TXGR3_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qgeminata_FLAB109.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qgeminata_FLAB109_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qfusiformis_TXMD3.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qfusiformis_TXMD3_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qgeminata_FLCK18.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qgeminata_FLCK18_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLAB109.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qgeminata_FLAB109_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qgeminata_FLSF54.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qgeminata_FLSF54_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLCK18.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qgeminata_FLCK18_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qgeminata_FLWO6.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qgeminata_FLWO6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLSF54.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qgeminata_FLSF54_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qhemisphaerica.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qhemisphaerica_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qgeminata_FLWO6.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qgeminata_FLWO6_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qminima_FLCK216.pkdat.gz | cut -f 1 > Qhemisphaerica_Qminima_FLCK216_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qhemisphaerica_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qhemisphaerica_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qhemisphaerica_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qhemisphaerica_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qhemisphaerica_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qhemisphaerica_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qhemisphaerica_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qhemisphaerica_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qhemisphaerica_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qhemisphaerica_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qhemisphaerica_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qhemisphaerica_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qhemisphaerica_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qhemisphaerica_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qhemisphaerica_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qhemisphaerica.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qhemisphaerica_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qminima_FLMO62.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qminima_FLMO62_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLCK216.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qminima_FLCK216_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qminima_FLSA185.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qminima_FLSA185_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLMO62.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qminima_FLMO62_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qminima_FLSF47.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qminima_FLSF47_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSA185.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qminima_FLSA185_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qnigra.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qnigra_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qminima_FLSF47.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qminima_FLSF47_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qoleoides_BZBB1.pkdat.gz | cut -f 1 > Qnigra_Qoleoides_BZBB1_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qnigra_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qnigra_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qnigra_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qnigra_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qnigra_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qnigra_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qnigra_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qnigra_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qnigra_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qnigra_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qnigra.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qnigra_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qoleoides_CRL0001.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qoleoides_CRL0001_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_BZBB1.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qoleoides_BZBB1_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qoleoides_CRL0030.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qoleoides_CRL0030_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0001.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qoleoides_CRL0001_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qoleoides_HNDA09.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qoleoides_HNDA09_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_CRL0030.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qoleoides_CRL0030_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_HNDA09.pkdat.gz Qoleoides_MXSA3017.pkdat.gz | cut -f 1 > Qoleoides_HNDA09_Qoleoides_MXSA3017_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_HNDA09.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qoleoides_HNDA09_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_HNDA09.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qoleoides_HNDA09_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_HNDA09.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qoleoides_HNDA09_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_HNDA09.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qoleoides_HNDA09_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_HNDA09.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qoleoides_HNDA09_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_HNDA09.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qoleoides_HNDA09_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_HNDA09.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qoleoides_HNDA09_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_MXSA3017.pkdat.gz Qsagraeana_CUCA4.pkdat.gz | cut -f 1 > Qoleoides_MXSA3017_Qsagraeana_CUCA4_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_MXSA3017.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qoleoides_MXSA3017_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_MXSA3017.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qoleoides_MXSA3017_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_MXSA3017.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qoleoides_MXSA3017_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_MXSA3017.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qoleoides_MXSA3017_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_MXSA3017.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qoleoides_MXSA3017_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qoleoides_MXSA3017.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qoleoides_MXSA3017_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUCA4.pkdat.gz Qsagraeana_CUSV6.pkdat.gz | cut -f 1 > Qsagraeana_CUCA4_Qsagraeana_CUSV6_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUCA4.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qsagraeana_CUCA4_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUCA4.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qsagraeana_CUCA4_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUCA4.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qsagraeana_CUCA4_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUCA4.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qsagraeana_CUCA4_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUCA4.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qsagraeana_CUCA4_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUSV6.pkdat.gz Qsagraeana_CUVN10.pkdat.gz | cut -f 1 > Qsagraeana_CUSV6_Qsagraeana_CUVN10_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUSV6.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qsagraeana_CUSV6_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUSV6.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qsagraeana_CUSV6_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUSV6.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qsagraeana_CUSV6_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUSV6.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qsagraeana_CUSV6_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUVN10.pkdat.gz Qvirginiana_FLBA140.pkdat.gz | cut -f 1 > Qsagraeana_CUVN10_Qvirginiana_FLBA140_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUVN10.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qsagraeana_CUVN10_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUVN10.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qsagraeana_CUVN10_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qsagraeana_CUVN10.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qsagraeana_CUVN10_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qvirginiana_FLBA140.pkdat.gz Qvirginiana_FLSF33.pkdat.gz | cut -f 1 > Qvirginiana_FLBA140_Qvirginiana_FLSF33_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qvirginiana_FLBA140.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qvirginiana_FLBA140_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qvirginiana_FLBA140.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qvirginiana_FLBA140_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qvirginiana_FLSF33.pkdat.gz Qvirginiana_LALC2.pkdat.gz | cut -f 1 > Qvirginiana_FLSF33_Qvirginiana_LALC2_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qvirginiana_FLSF33.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qvirginiana_FLSF33_Qvirginiana_SCCU3_k21.kmer
kmer_merge -k s -c -d '0' -A A -B A Qvirginiana_LALC2.pkdat.gz Qvirginiana_SCCU3.pkdat.gz | cut -f 1 > Qvirginiana_LALC2_Qvirginiana_SCCU3_k21.kmer
